services:
  postgres:
    image: postgres:15
    container_name: nasa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/nasa_analytics.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:6
    container_name: nasa-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  hive-server:
    image: apache/hive:3.1.3
    container_name: nasa-hive
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_CONF_hive_metastore_warehouse_dir: /opt/hive/data/warehouse
    ports:
      - "10000:10000"
    volumes:
      - ./hive_data:/tmp/nasa_logs_hive
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 10000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  mongo-app:
    build: .
    container_name: mongo-app
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true

  hive-app:
    build: .
    container_name: hive-app
    depends_on:
      postgres:
        condition: service_healthy
      hive-server:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./hive_data:/tmp/nasa_logs_hive
    stdin_open: true
    tty: true

  pig-app:
    build: .
    container_name: pig-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true

  mr-app:
    build: .
    container_name: mr-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./mr_data:/tmp/nasa_logs_mr
    stdin_open: true
    tty: true

volumes:
  pgdata:
  mongodata: